src/verbum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

import crm.views as crm_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("login", crm_views.login_view, name="login"),
    path("logout", crm_views.logout_view, name="logout"),
    path("paywall/", crm_views.paywall_registration, name="paywall"),
    path(
        "paywall-finalize/<str:hash_>/",
        crm_views.paywall_finalize,
        name="paywall-finalize",
    ),
    # path("api/crm/mailchimp/", crm.views.mailchimp_change),
    # path("api/stripe/create-checkout-session/", crm_views.create_checkout_session_view),
    path("api/stripe/webhook-received/", crm_views.webhook_received),
    path("", include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/home/models.py
import stripe
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models, transaction
from django.db.models import Max
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from modelcluster.contrib.taggit import ClusterTaggableManager
from modelcluster.fields import ParentalKey
from taggit.models import Tag, TaggedItemBase
from wagtail.admin.edit_handlers import (FieldPanel, InlinePanel,
                                         MultiFieldPanel, PageChooserPanel,
                                         StreamFieldPanel)
from wagtail.contrib.routable_page.models import RoutablePageMixin, route
from wagtail.core import blocks
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Orderable, Page
from wagtail.core.wagtail_hooks import check_view_restrictions
from wagtail.embeds.blocks import EmbedBlock
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtailmetadata.models import MetadataPageMixin

from crm.forms import OrderForm, PaywallForm
from crm.models import Order, Subscriber


class HomePage(Page):
    pinned_article = models.ForeignKey(
        "home.Article",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        help_text="Used as 'Essay of the week'",
    )

    subpage_types = [
        "home.ArticleIndex",
        "home.ArticleTagIndex",
        "home.AuthorIndex",
        "home.CategoryIndex",
        "home.GenericPage",
    ]

    content_panels = Page.content_panels + [
        PageChooserPanel("pinned_article"),
    ]

    def articles(self):
        return Article.objects.live().order_by("-date", "-pk")

    def articles_without_pinned(self):
        return self.articles().exclude(pk=self.pinned_article)

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["article_index"] = (
            self.get_children().type(ArticleIndex).specific().first()
        )
        context["most_viewed"] = self.articles().order_by("-view_count")
        return context


class GenericPage(Page):
    """Provides possibility to create a page with any content"""

    body = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel("body"),
    ]


class AuthorIndex(Page):
    subpage_types = ["home.Author"]


class Author(MetadataPageMixin, Page):
    first_name = models.CharField(max_length=64, blank=True)
    last_name = models.CharField(max_length=64)
    photo = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    description = RichTextField(blank=True)

    schemaorg_type = "Page"
    promote_panels = Page.promote_panels + MetadataPageMixin.panels
    content_panels = Page.content_panels + [
        FieldPanel("first_name"),
        FieldPanel("last_name"),
        ImageChooserPanel("photo"),
        FieldPanel("description"),
    ]

    def name(self):
        return f"{self.first_name} {self.last_name}"

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["articles"] = paginated_articles(
            Article.objects.filter(authors__author=self).live().public(), request
        )
        return context


class Category(Page):
    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        articles = (
            Article.objects.live()
            .filter(article_category=self)
            .order_by("-date", "-pk")
        )
        context["articles"] = paginated_articles(articles, request)
        return context


class CategoryIndex(Page):
    subpage_types = ["home.Category"]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["categories"] = self.get_children().live().public()
        return context


class ArticleTag(TaggedItemBase):
    content_object = ParentalKey(
        "Article", related_name="tagged_items", on_delete=models.CASCADE
    )


class Article(MetadataPageMixin, Page):
    article_id = models.IntegerField(unique=True)
    main_image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    date = models.DateField(
        "Post date",
        db_index=True,
        help_text="Slúži len na zobrazenie. "
        "Oddialenie publikovania nájdeš v nastaveniach.",
    )
    article_category = models.ForeignKey(
        "home.Category",
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name="articles",
        verbose_name="category",
    )
    tags = ClusterTaggableManager(through=ArticleTag, blank=True)
    view_count = models.PositiveBigIntegerField(default=0, db_index=True)

    free_content = StreamField(
        [
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("embed", EmbedBlock(help_text="Youtube, Twitter, Vimeo a iné.")),
            (
                "quote",
                blocks.StructBlock(
                    [("text", blocks.TextBlock()), ("author", blocks.CharBlock())],
                    template="home/blocks/quote.html",
                ),
            ),
        ],
        blank=True,
    )
    paid_content = StreamField(
        [
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("embed", EmbedBlock(help_text="Youtube, Twitter, Vimeo a iné.")),
        ],
        blank=True,
    )

    schemaorg_type = "Page"
    promote_panels = Page.promote_panels + MetadataPageMixin.panels
    content_panels = Page.content_panels + [
        MultiFieldPanel(
            [
                FieldPanel("date"),
                PageChooserPanel("article_category"),
                FieldPanel("tags"),
            ],
            heading="Basic information",
        ),
        ImageChooserPanel("main_image"),
        InlinePanel("authors", heading="authors"),
        StreamFieldPanel("free_content"),
        StreamFieldPanel("paid_content"),
    ]

    parent_page_types = ["home.ArticleIndex"]

    def get_url_parts(self, request=None):
        """Insert article_id to url"""
        site_id, root_url, page_path = super().get_url_parts(request)
        page_path = page_path.split("/")
        page_path.insert(-2, str(self.article_id))
        page_path = "/".join(page_path)
        return site_id, root_url, page_path

    def save(self, clean=True, user=None, log_action=False, **kwargs):
        with transaction.atomic():
            if self.article_id is None:
                max_id = Article.objects.aggregate(max=Max("article_id"))["max"] or 0
                self.article_id = max_id + 1
            return super().save(clean, user, log_action, **kwargs)

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["tags_page"] = ArticleTagIndex.objects.live().last()
        context["paywall_form"] = PaywallForm()
        context["articles_in_category"] = (
            self.article_category.articles.live()
            .public()
            .order_by("-date")
            .exclude(pk=self.pk)
        )
        context["most_viewed"] = Article.objects.live().public().order_by("-view_count")
        return context


class AuthorSequence(Orderable):
    article = ParentalKey(Article, on_delete=models.CASCADE, related_name="authors")
    author = models.ForeignKey(
        Author,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="articles",
    )


class ArticleIndex(RoutablePageMixin, Page):
    subpage_types = ["home.Article"]

    @route(r"^(\d+)/(.+)/")
    def article_with_id_in_url(self, request, article_id, slug):
        article = Article.objects.get(article_id=article_id)
        result = check_view_restrictions(
            article, request, serve_args=None, serve_kwargs=None
        )
        if isinstance(result, HttpResponse):
            return result
        if slug == article.slug:
            return article.serve(request)
        return redirect(article.get_url(request))

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        all_articles = (
            Article.objects.live().public().child_of(self).order_by("-date", "-pk")
        )
        context["articles"] = paginated_articles(all_articles, request)
        return context


class ArticleTagIndex(RoutablePageMixin, Page):
    @route(r"^(.+)/")
    def articles_by_tag(self, request, slug):
        articles = (
            Article.objects.live().filter(tags__slug=slug).order_by("-date", "-pk")
        )
        articles = paginated_articles(articles, request)
        return self.render(
            request,
            template="home/article_index.html",
            context_overrides={"articles": articles},
        )

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["tags"] = Tag.objects.order_by("name").values_list("name", "slug")
        return context


class SubscriptionPage(Page):
    description = RichTextField()
    success_message = RichTextField()

    description_free = RichTextField()
    description_digital = RichTextField()
    description_premium = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel("description"),

src/crm/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crm.models import Order, User


class UserForm(forms.ModelForm):
    """For registration of user when he buys a subscription"""

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password"]


class OrderForm(forms.ModelForm):
    plan = forms.ChoiceField()

    def __init__(self, plan_choices=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if plan_choices:
            self.fields["plan"].choices = plan_choices

    class Meta:
        model = Order
        fields = ["plan", "first_name", "last_name", "email", "password"]
        widgets = {
            "password": forms.PasswordInput(),
        }


class PaywallForm(forms.Form):
    email = forms.EmailField(
        max_length=255,
        widget=forms.EmailInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "E-mail",
            }
        ),
    )
    target_url = forms.URLField(widget=forms.HiddenInput())

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email bol už zaregistrovaný")
        return email


class PaywallFinalizeForm(forms.Form):
    first_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "Meno",
            }
        ),
    )
    last_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "Priezvisko",
            }
        ),
    )
    password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "Heslo",
            }
        ),
    )


class LoginForm(forms.Form):
    email = forms.EmailField(
        max_length=255,
        widget=forms.EmailInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "E-mail",
            }
        ),
    )
    password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "class": "mb-5 p-1 w-full sm:w-9/12 border border-gray-200 text-center",
                "placeholder": "Heslo",
            }
        ),
    )

src/frontend/templates/home/archive.html
{% extends "home/base.html" %}
{% load wagtailimages_tags %}
{% load wagtailroutablepage_tags %}
{% load wagtailcore_tags %}
{% load static %}

{% block body_class %}template-archive{% endblock %}

{% block content %}
  <main>
    <div class="row">
      <div class="col d-flex flex-row align-items-center my-2">
        <div class="text-uppercase me-3 f-special subtitle">
          Časopis pre kresťanskú kultúru
        </div>
        <div class="flex-grow-1">
          <hr>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8 mb-3">
        <h1 class="fw-bold">{{ page.title }}</h1>
        {{ page.body|richtext }}
      </div>
    </div>
    <div class="row">
      {% for issue in page.issues.all %}
        <div class="col-md-3 col-sm-6">
          <div class="d-flex flex-column align-items-center">
            <a href="{{ issue.file.url }}" class="mb-2">
              {% image issue.cover width-175 %}
            </a>
            <div class="text-center">
              {{ issue.caption }}
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
  </main>
{% endblock content %}

src/frontend/templates/home/article.html
{% extends "home/base.html" %}
{% load wagtailimages_tags wagtailcore_tags %}

{% block body_class %}template-article{% endblock %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
  <article class="max-w-screen-lg mb-4 flex flex-col">
    {% image page.main_image fill-1100x500 format-jpeg class='w-full object-fit object-center mb-10 order-1' %}

    <div class="grid grid-cols-1 sm:grid-cols-3 order-4">
      <h1 class="sm:col-span-2 mb-5 f-spec font-medium text-4xl uppercase">{{ page.title }}</h1>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-3 gap-10 md:gap-20 default-formatting order-5">
      <div class="sm:col-span-2 leading-7 article-content">
        {% include_block page.free_content %}
        {% if page.paid_content %}
          {% if user.is_authenticated %}
            {% include_block page.paid_content %}
          {% else %}
            <div class="border border-gray-200 sm:m-8 px-4 md:px-8 py-5 text-center f-spec">
              <div class="mb-2">
                Na dočítanie článku je potrebné zadať Váš e-mail.
              </div>
              <div class="mb-2">
                Časopis Verbum tvoríme pre ľudí, ktorí majú záujem o kvalitné čitanie a diskusiu.
                Chceme budovať komunitu čitateľov, ktorí budú spolu s nami tvorcami kultúry a
                kultúrnosti. Vyplnením e-mailu získate prístup k textom a dozviete sa o našich
                novinkách ako prví.
              </div>
              <div class="mb-5">
                Váš e-mail a ďalšie údaje nikdy neposkytneme ďalším stranám.
              </div>

              <form action="{% url "paywall" %}" method="post"
                    class="flex flex-col mb-5 items-center">
                {% csrf_token %}
                {% with paywall_form as form %}
                  {{ form.non_field_errors }}
                  {{ form.email.errors }}
                  {{ form.email }}
                  <input type="hidden" name="target_url" value="{{ page.full_url }}" id="id_target_url">
                {% endwith %}
                <div class="flex justify-center">
                  <button type="submit"
                          class="px-6 py-2 bg-black f-spec font-medium text-white">
                    Registrovať
                  </button>
                </div>
              </form>

              <div class="mb-5 text-sm text-gray-400">
                Odoslaním súhlasite s našimi
                <a href="/gdpr/" class="text-gray-700">GDPR</a> a
                <a href="/obchodne-podmienky/" class="text-gray-700">Obchodnými podmienkami</a>.
              </div>
            </div>
          {% endif %}
        {% endif %}
      </div>
      <div class="f-spec">
        {% for author_link in page.authors.all %}
          <a href="{{ author_link.author.url }}"
             class="font-medium">{{ author_link.author.name }}</a>
          <div class="mb-5">
            {{ author_link.author.description|richtext }}
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="text-gray-500 mb-3 order-2">
      {% for tag in page.tags.all %}
        <a href="/tagy/{{ tag.slug }}">#{{ tag.name }}</a>
      {% endfor %}
    </div>

    <address rel="author" class="text-xl not-italic mb-2 order-3">
      {% for author_link in page.authors.all %}
        {{ author_link.author.name }}{% if not forloop.last %},{% endif %}
      {% endfor %}
      <span class="mx-3">&middot;</span>
      <span class="text-lg text-gray-700">{{ page.date|date:"SHORT_DATE_FORMAT" }}</span>
    </address>
  </article>

  <section>
    <div class="mb-4 f-spec uppercase text-lg">Ďalšie texty z rubriky</div>

    <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 sm:gap-10 lg:grid-cols-3 xl:grid-cols-4">
      {% for article in articles_in_category|slice:':3' %}
        <article class="flex flex-col">
          {% image article.main_image height-250 format-jpeg as article_img %}
          <a href="{{ article.url }}" class="mb-3">
            <img src="{{ article_img.url }}" alt="{{ article_img.alt }}"
                 class="w-full h-32 sm:h-44 object-cover object-center">
          </a>

          <address rel="author" class="not-italic mb-2">
            {% for author_link in article.authors.all %}
              {{ author_link.author.name }}{% if not forloop.last %},{% endif %}
            {% endfor %}
          </address>

          <h2 class="mb-2 f-spec font-medium uppercase text-lg leading-tight">
            <a href="{{ article.url }}">
              {{ article.title }}
            </a>
          </h2>
        </article>
      {% endfor %}

      <div class="bg-gray-200 f-spec p-5
                  sm:row-start-1 sm:col-start-2 lg:col-start-3 xl:col-start-4">
        <h2 class="text-lg mb-4">Najčítanejšie</h2>
        <ol class="text-sm list-decimal ml-4">
          {% for article in most_viewed|slice:':7' %}
            <li><a href="{{ article.url }}" class="line-clamp-1">{{ article.title }}</a></li>
          {% endfor %}
        </ol>
      </div>
    </div>
  </section>
{% endblock content %}

src/frontend/templates/home/article_grid.html
{% load wagtailimages_tags %}


<div class="grid grid-cols-1 gap-5 sm:grid-cols-2 sm:gap-10 lg:grid-cols-3 xl:grid-cols-4 mb-8">
  {% for article in articles %}
    <article class="flex flex-col">
      <address rel="author" class="not-italic mb-2">
        {% for author_link in article.authors.all %}
          {{ author_link.author.name }}{% if not forloop.last %},{% endif %}
        {% endfor %}
      </address>

      <h2 class="mb-2 f-spec font-medium uppercase text-lg leading-tight">
        <a href="{{ article.url }}">
          {{ article.title }}
        </a>
      </h2>
      {% image article.main_image height-250 format-jpeg as article_img %}
      <a href="{{ article.url }}" class="mt-auto">
        <img src="{{ article_img.url }}" alt="{{ article_img.alt }}"
             class="w-full h-32 sm:h-44 object-cover object-center">
      </a>
    </article>
  {% endfor %}
</div>

{% if articles.paginator.num_pages > 1 %}
  <div class="flex justify-center">
    {% if articles.has_previous %}
      <a href="?page={{ articles.previous_page_number }}"
         class="mx-2 px-6 py-2 bg-black f-spec font-medium text-white">
        <span>&laquo; Novšie</span>
      </a>
    {% endif %}
    {% if articles.has_next %}
      <a href="?page={{ articles.next_page_number }}"
         class="mx-2 px-6 py-2 bg-black f-spec font-medium text-white">
        <span>Staršie &raquo;</span>
      </a>
    {% endif %}
  </div>
{% endif %}

src/frontend/templates/home/article_tag_index.html
{% extends "home/base.html" %}

{% block body_class %}template-article-index{% endblock %}

{% block content %}
  <div class="mb-4 f-spec uppercase text-lg">Všetky tagy</div>
  <div class="max-w-xl text-gray-500 mb-3">
      {% for name, slug in tags %}
        <a href="/tagy/{{ slug }}">#{{ name }}</a>
      {% endfor %}
  </div>
{% endblock content %}

src/frontend/templates/home/author.html
{% extends "home/base.html" %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% block body_class %}template-author{% endblock %}

{% block content %}
  {% image page.photo original format-jpeg as pinned_bg %}
  <article class="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-10 mb-10">
    <img src="{{ pinned_bg.url }}" alt="{{ pinned_bg.alt }}"
         class="h-48 sm:h-72 w-full object-cover object-center">
    <div>
      <h1 class="f-spec font-medium uppercase text-4xl mb-2">
        {{ page.title }}
      </h1>
      <div class="default-formatting">
        {{ page.description|richtext }}
      </div>
    </div>
  </article>

  <div class="mb-4 f-spec uppercase text-lg">Texty autora</div>
  {% include "home/article_grid.html" %}
{% endblock content %}

src/frontend/templates/home/base.html
{% load django_vite static wagtailuserbar meta %}
<!DOCTYPE html>
<html lang="sk" {% meta_namespaces_schemaorg %}>
<head {% meta_namespaces %}>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}
      {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
    {% endblock %}
    {% block title_suffix %}
      {% with self.get_site.site_name as site_name %}
        {% if site_name %}- {{ site_name }}{% endif %}
      {% endwith %}
    {% endblock %}
  </title>
  {% include "meta/meta.html" %}

  {# Global stylesheets #}
  {% vite_hmr_client %}
  {% vite_asset 'main.js' %}

  <link rel='shortcut icon' type='image/x-icon' href='{% static 'favicon.ico' %}'/>

  {% block extra_css %}
    {# Override this in templates to add extra stylesheets #}
  {% endblock %}
</head>

<body class="flex flex-col min-h-screen f-norm px-4 {% block body_class %}{% endblock %}">
{% wagtailuserbar %}

<div class="container mx-auto my-10 flex-grow">
  <header class="flex flex-row justify-center sm:justify-start uppercase mb-10 f-spec">
    <a href="/" class="flex flex-row">
      <svg class="fill-current text-black" width="33" viewBox="0 0 78.38 81.73">
        {% include "home/logo.html" %}
      </svg>
      <span class="text-5xl mx-5">Verbum</span>
    </a>
    {% include "home/navigation.html" %}
  </header>

  <main>
    {% block content %}{% endblock %}
  </main>
</div>

<div class="bg-black text-white -mx-4 px-4 py-10 uppercase text-xs">
  <footer class="container mx-auto grid grid-cols-2 lg:grid-cols-4 gap-5 lg:gap-10
                 f-spec font-medium leading-loose">
    <div class="flex flex-col">
      <svg class="fill-current text-white" width="20" viewBox="0 0 78.38 81.73">
        {% include "home/logo.html" %}
      </svg>
      Verbum &dash; časopis pre kresťanskú kultúru
    </div>
    <div class="flex flex-col">
      <a href="/o-casopise">O časopise</a>
      <a href="/redakcia">Redakcia</a>
      <a href="https://old.verbumcasopis.sk" target="_blank">Starý web</a>
    </div>
    <div class="flex flex-col">
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Odhlásiť sa</a>
      {% else %}
        <a href="{% url 'login' %}">Prihlásiť sa</a>
      {% endif %}
    </div>
    <div class="flex flex-col">
      <a href="https://www.facebook.com/Verbum-%C4%8Dasopis-pre-kres%C5%A5ansk%C3%BA-kult%C3%BAru-541132596033735/">
        Facebook
      </a>
      <a href="https://www.instagram.com/spolocenstvo.ladislava.hanusa/">Instagram</a>
    </div>
  </footer>
</div>

{% block extra_js %}
  {# Override this in templates to add extra javascript #}
{% endblock %}

{# Global site tag (gtag.js) - Google Analytics #}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-40K0CGJQ4R"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag('config', 'G-40K0CGJQ4R');
</script>
</body>
</html>

src/frontend/templates/home/category.html
{% extends "home/base.html" %}

{% block body_class %}template-category{% endblock %}

{% block content %}
  <div class="mb-4 f-spec uppercase text-lg">Všetky texty v rubrike</div>
  {% include "home/article_grid.html" %}
{% endblock content %}

src/frontend/templates/home/category_index.html
{% extends "home/base.html" %}
{% load wagtailcore_tags %}

{% block body_class %}template-category-index{% endblock %}

{% block content %}
  <div class="mb-4 f-spec uppercase text-lg">Všetky rubriky</div>
  <div class="max-w-xl mb-3 text-xl">
      {% for category in categories %}
        <a href="{% pageurl category %}">{{ category.title }}</a>
      {% endfor %}
  </div>
{% endblock content %}

src/frontend/templates/home/login.html
{% extends "home/base.html" %}
{% load i18n %}

{% block content %}
  <div class="max-w-screen-lg">
    {% if messages %}
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <div class="text-green-500 bg-green-200 border border-green-400 p-4 m-5">
            {{ message }}
          </div>
        {% else %}
          <div class="text-error-500 bg-error-200 border border-error-400 p-4 m-5">
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}

    {% if form %}
      {% if form.errors %}
        <div class="text-red-500 bg-red-200 border border-red-400 p-4 m-5">
          {% trans "Your username and password didn't match. Please try again." %}
        </div>
      {% endif %}
      <form action="{% url 'login' %}" method="post" class="flex flex-col mb-5 items-center">
        {% csrf_token %}
        {{ form.email }}
        {{ form.password }}
        <div class="flex justify-center">
          <button type="submit"
                  class="px-6 py-2 bg-black f-spec font-medium text-white">
            Prihlásiť
          </button>
        </div>
      </form>
    {% endif %}
  </div>
{% endblock content %}

src/frontend/templates/home/logout.html
{% extends "home/base.html" %}

{% block content %}
  <div class="text-green-500 bg-green-200 border border-green-400 p-4 m-5">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}